#!/bin/bash

echo "🧪 Testing Custom Agent Access"
echo "==============================="

echo ""
echo "1. Starting the application..."
echo "   Run: npm run dev"
echo ""
echo "2. Open browser and go to: http://localhost:3000"
echo ""
echo "3. Steps to test custom agent access:"
echo "   a) Click 'API Key' and add your OpenRouter API key"
echo "   b) Click 'Add Agent' to create a new agent"
echo "   c) Fill in the required fields and click 'Create Agent'"
echo "   d) You should see your new agent appear on the main page"
echo "   e) Click on your custom agent to access it"
echo ""
echo "4. If you still can't access your custom agent:"
echo "   a) Check browser console (F12) for errors"
echo "   b) Verify the agent was created in the database"
echo "   c) Make sure you're logged in (look for auth_token in localStorage)"
echo ""
echo "💡 Debugging Commands:"
echo "   - Check database: npm run db:studio"
echo "   - View logs: Check browser console and terminal output"
echo "   - Reset database: npm run db:reset (⚠️  This will delete all data!)"
echo ""
echo "🔍 Common Issues:"
echo "   - Agent not showing: Refresh the page after creation"
echo "   - Can't access agent: Make sure you're authenticated"
echo "   - Database errors: Run 'npm run setup' to reinitialize"
echo ""
echo "📞 If problems persist:"
echo "   1. Check that Prisma is working: npx prisma studio"
echo "   2. Verify your custom agent exists in the Agent table"
echo "   3. Check the isActive field is true"
echo "   4. Ensure your userId matches the agent's userId"
